@startuml
skinparam linetype polyline
skinparam linetype ortho
left to right direction

actor "Card Holders" as user
agent "Merchants \n(Bank accounts)" as merchant
package "Card Network / Card Scheme / Clearing" as ccnet {
  agent "VISA" as visa
  agent "MasterCard" as mc
  agent "JCB" as jcb
  agent "American Express" as axp
}
package "Regional Card Network / Clearing" as ccnet_local {
  agent "NCCC" as nccc #lightcoral
  agent "FISC" as fisc #orange
}
package "Global Issuing Bank" as issuer_global {
  agent "Bank G" as issuer_global_a
}
package "Regional Issuing Bank" as issuer_local {
  agent "Bank A" as issuer_a
  agent "Bank C" as issuer_b
  agent "Bank B" as issuer_c
}
package "Regional Acquiring Bank" as acquirer_local {
  agent "Bank A" as acquirer_a
  agent "Bank C" as acquirer_b
  agent "Bank B" as acquirer_c
}

nccc - fisc: Clearing Routing
nccc --[#brown] visa: Clearing Routing
nccc --[#brown] mc
nccc --[#brown] jcb
nccc --[#brown] axp
fisc --[#darkGoldenRod] visa
fisc --[#darkGoldenRod] mc
fisc -[#darkGoldenRod] jcb

issuer_a --[#brown]> nccc: Clearing for Issuing
acquirer_a <--[#brown] nccc
issuer_b --[#darkGoldenRod]> fisc
acquirer_b <--[#darkGoldenRod] fisc: Clearing for Acquiring\n(Interchange fee deducted)
issuer_c --[#brown]> nccc
acquirer_c <--[#darkGoldenRod] fisc

issuer_global_a -right-> visa
issuer_global_a -right-> mc
issuer_global_a -right-> axp: Clearing for Issuing

acquirer_local ---> merchant: Settlement\n(MDR deducted)

user --> issuer_global: Card billing
user -> issuer_local
@enduml
